name: Verify

on: [push, pull_request]

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm prettier --check "**/*.js"

  generate:
    name: Parser Generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - name: Generate parser from source code
        run: pnpm generate
      - name: Check if there are changes
        id: git-changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: Fail if there are changes
        if: steps.git-changes.outputs.changed == 1
        run: exit 1

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm test
